baseurl = "https://gohugo.io/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3

# customized for expo

defaultContentLanguage = "en"

sectionPagesMenu = "main"

pygmentsOptions = "linenos=1"
pygmentsCodefences = true
pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  date_format = "2006/01/02"
  #bulmaswatch = "cosmo"

[params.navbar]
  style = "is-dark"

[params.landingpage]
  start = "/guide"
  #style = "is-primary"
  subtitle = "How to work with Hugo"